version: "2"
run:
  go: "1.22"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    goheader:
      values:
        regexp:
          license-year: (202[0-9]|20[3-9][0-9])
      template: |-
        Copyright {{license-year}} The Kubernetes Authors.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: utilruntime
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
        - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
          alias: clusterv1
        - pkg: sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3
          alias: clusterctlv1
        - pkg: sigs.k8s.io/cluster-api/cmd/clusterctl/client/config
          alias: configclient
        - pkg: sigs.k8s.io/cluster-api-addon-provider-helm
          alias: addonsv1alpha1
      no-unaliased: true
    nlreturn:
      block-size: 2
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
      dot-import-whitelist:
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - goheader
        path: hack/boilerplate
      - path: (.+)\.go$
        text: 'missing cases in switch of type v1.PlatformType: (\.*)'
    paths:
      - zz_generated.*\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - third_party$
      - builtin$
      - examples$
