name: PR title verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: verify PR contents
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0
    - name: Check if PR title is valid
      # Don't run this step on PRs created by the cherry-pick bot,
      # as the PR description is too short, but otherwise the PRs are fine.
      if: ${{ github.event.pull_request.head.repo.owner.login != 'k8s-infra-cherrypick-robot' }}
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        ./hack/verify-pr-title.sh "${PR_TITLE}"
