name: Lint YAML files

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag=v6.0.3

      - name: Lint YAML files
        run: yamllint -c .github/yamllint_config.yaml .

